/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghost;

import static ghost.ModificarDatos.txtUsuarioAnterior;
import static ghost.ModificarDatos.txtUsuarioNuevo;

/**
 *
 * @author Delia
 */
public class MiPerfil extends javax.swing.JFrame {

    /**
     * Creates new form MiPerfil
     */
    public MiPerfil() {
        initComponents();
        
        setTitle("Mi Perfil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuserperfil = new javax.swing.JLabel();
        btnModificarMisDatos = new javax.swing.JButton();
        btnVerMisDatos = new javax.swing.JButton();
        lblcontraseñaperfil = new javax.swing.JLabel();
        lblUsuarioNuevo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnModificarMisDatos.setText("b.Modificar mis datos");
        btnModificarMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMisDatosActionPerformed(evt);
            }
        });

        btnVerMisDatos.setText("Ver Mis Datos");
        btnVerMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMisDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtuserperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarMisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(btnVerMisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcontraseñaperfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuarioNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnVerMisDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtuserperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblcontraseñaperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarMisDatos)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMisDatosActionPerformed
        // TODO add your handling code here:
        ModificarDatos md = new ModificarDatos();
        md.setVisible(true);
        
    }//GEN-LAST:event_btnModificarMisDatosActionPerformed

    private void btnVerMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMisDatosActionPerformed
        // TODO add your handling code here:
        String usuario = " ";
        String contraseñas = " ";
         if(variables.userLogin.equalsIgnoreCase(usuario)  ){
          //MiPerfil.txtuserperfil.setText("Usuario : " + CreateUser.txtUser.getText());
           
           MiPerfil.txtuserperfil.setText("Usuario :  ");
          }else{
          
          MiPerfil.txtuserperfil.setText("Usuario : " + CreateUser.txtUser.getText());
           //MiPerfil.txtuserperfil.setText("Usuario :  ");
          }
         
          
    }//GEN-LAST:event_btnVerMisDatosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
        
        
            for(int cont = 0; cont < variables.usuarios.length; cont++){
                if(txtUsuarioAnterior.getText().equalsIgnoreCase(variables.usuarios[cont])){
                    variables.usuarios[cont] = null;
                    
                }          
                                    
            
        } 
             if(variables.usuarios == null){
            variables.usuarios[variables.i]=txtUsuarioNuevo.getText();
            }  
        
            MiPerfil.lblUsuarioNuevo.setText("Usuario Nuevo : " + ModificarDatos.txtUsuarioNuevo.getText());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarMisDatos;
    private javax.swing.JButton btnVerMisDatos;
    public static javax.swing.JLabel lblUsuarioNuevo;
    public static javax.swing.JLabel lblcontraseñaperfil;
    public static javax.swing.JLabel txtuserperfil;
    // End of variables declaration//GEN-END:variables
}
